/** @type {import('tailwindcss').Config} */
export const content = [
  "./app/**/*.{js,ts,jsx,tsx,mdx}",
  "./components/**/*.{js,ts,jsx,tsx,mdx}",
  "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
];
export const darkMode = "class";
export const theme = {
  extend: {
    colors: {
      "secondary-dim": "#bb87f1",
      "on-primary-fixed": "#000000",
      "surface-tint": "#ba9eff",
      "secondary-container": "#5e2c91",
      "error-dim": "#d73357",
      "on-secondary-fixed-variant": "#69379c",
      "tertiary-fixed-dim": "#f67ca3",
      "on-surface": "#ffffff",
      "on-tertiary": "#6a0934",
      "surface-dim": "#0e0e0e",
      "primary-fixed-dim": "#a27cff",
      "on-secondary-fixed": "#4b147d",
      "on-primary": "#39008c",
      surface: "#0e0e0e",
      background: "#0e0e0e",
      "on-surface-variant": "#adaaaa",
      "surface-container-highest": "#262626",
      "inverse-on-surface": "#565555",
      "tertiary-container": "#fd81a8",
      "on-tertiary-fixed": "#380018",
      "on-secondary": "#390068",
      "surface-variant": "#262626",
      "surface-container-high": "#20201f",
      "on-error": "#490013",
      "outline-variant": "#484847",
      outline: "#767575",
      "on-background": "#ffffff",
      "error-container": "#a70138",
      error: "#ff6e84",
      "surface-container-low": "#131313",
      "surface-bright": "#2c2c2c",
      "on-error-container": "#ffb2b9",
      "primary-fixed": "#ae8dff",
      "secondary-fixed-dim": "#dab4ff",
      "on-secondary-container": "#e3c4ff",
      "on-primary-fixed-variant": "#370086",
      "secondary-fixed": "#e4c6ff",
      tertiary: "#ff97b5",
      "tertiary-dim": "#f0779d",
      "on-tertiary-fixed-variant": "#701039",
      "surface-container-lowest": "#000000",
      secondary: "#c08cf7",
      "inverse-surface": "#fcf9f8",
      "primary-dim": "#8455ef",
      "inverse-primary": "#6e3bd7",
      "tertiary-fixed": "#ff8eb0",
      "on-primary-container": "#2b006e",
      "primary-container": "#ae8dff",
      "on-tertiary-container": "#59002a",
      "surface-container": "#1a1a1a",
      primary: "#ba9eff",
    },
    borderRadius: {
      DEFAULT: "0.25rem",
      lg: "0.5rem",
      xl: "0.75rem",
      full: "9999px",
    },
    fontFamily: {
      headline: ["Inter"],
      body: ["Inter"],
      label: ["Inter"],
    },
  },
};
export const plugins = [
  require("@tailwindcss/forms"),
  require("@tailwindcss/container-queries"),
];
