services:
  redisinsight:
    image: redis/redisinsight:latest

    ports:
      - "5540:5540"

    networks:
      - adda_network

    volumes:
      - redisinsight:/data

volumes:
  redisinsight:

networks:
  adda_network:
    external: true
    name: adda_adda_network
